### ISSUE TITLE
Determine high-level architecture for nodes

### ISSUE THREAD

**Issue by djpetti** [djpetti/csci6780#43]

**Comment by Nickster258** [comment]
Two quick things of note:

1. In lieu of making two individual input parsers for each nameserver and bootstrap server, I opted in "embedding" that functionality into the corresponding classes. I am still not sure if this method is ideal here, but it was a thought that I went for in the moment.
2. The current approach has _one_ executable. You specify if it is a "simple" nameserver or a bootstrap nameserver with an argument. While this technically doesn't abide by the project guidelines, the guidelines themselves said they are flexible.
